### ISSUE TITLE
ReferenceError: getFromPage is not defined

### ISSUE THREAD

**Issue by ryanjbonnell** [larixk/slack-file-deleter#1]
When I attempt to run this package, it fails with the following error message:

```
ReferenceError: getFromPage is not defined
```

To replicate the issue, run the example command from the README to list all files visible to a user associated with a token:

`$ node index.js -t abcd-0123456789-0123456789-0123456789-0123456abc -l`

The full content of the error message is below:

``` shell
Fetching files: 50%
~/Desktop/slack/index.js:75
    getFromPage(pageNumber + 1);
    ^

ReferenceError: getFromPage is not defined
    at Request._callback (~/Desktop/slack/index.js:75:5)
    at Request.self.callback (~/Desktop/slack/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (~/Desktop/slack/node_modules/request/request.js:1041:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (~/Desktop/slack/node_modules/request/request.js:968:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

**Comment by ryanjbonnell** [comment]
Please refer to the [pull request I submitted](https://github.com/larixk/slack-file-deleter/pull/2) for a fix.
